### PR TITLE
Create Strings.xml for Chinese

### PR DESCRIPTION
**Pull request by sr093906**

### CODE REVIEW

**Comment by fi3te** [comment]
Hi sr093906,

thank you very much for your translations!

Could you please remove the lines with 'translatable="false"'?
It is sufficient if they only appear in the main file.

Best regards,
Fiete

**Review by fi3te — CHANGES_REQUESTED** [review]
See previous comment

**Comment by sr093906** [comment]
@fi3te Thanks for reply. I intentionally leave them in the file to facilitate future maintenance (line numbers). If you insist, I can remove them though.

**Comment by fi3te** [comment]
Yes, please remove these lines. For me it's ok if you move the English entries of example_x_expression to the end of the file.

**Comment by sr093906** [comment]
@fi3te Done.

**Review by fi3te — APPROVED** [review]

**Pull request merged**
